// 什么时候应该使用panic ？
// 不可恢复的错误
// 在定义一个可能失败的函数的时候，优先考虑返回Result
// 否则就是panic！
fn main() {}
